name: fitness_dashboard_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.5
  http: ^1.2.1
  get: ^4.6.6
  awesome_dialog: ^3.2.1
  flutter_background_service: ^5.0.6
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.4.0
  auto_route: ^8.1.3
  syncfusion_flutter_gauges: ^24.1.44

  syncfusion_flutter_charts: ^24.1.45
  toggle_switch: ^2.3.0
  fl_chart: ^0.68.0
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  flutter_advanced_drawer: ^1.3.6
  quickalert: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  loading_animation_widget: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: KulimPark
      fonts:
        - asset: assets/fonts/KulimPark-Regular.ttf
